### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by maverick74** [ikapelyukhin/opensuse-migration#1]
Looks pretty nice from the video.

I have a few questions regarding it: 

1. is there going to be a user notification about a leap new version?
2. I noticed the lack of the option to migrate to tumbleweed... is it coming later?
3. Where is the GUI going to be integrated (yast-migration or a new yast module)?

Thanks :)

**Comment by ikapelyukhin** [comment]
Hi, @maverick74.

> Looks pretty nice from the video.

Feel free to try it out yourself. `zypper dup` is what actually does the migration. Unless you actually run `zypper dup` -- you can switch back and forth between the openSUSE versions without any harm to your system.



>  1. is there going to be a user notification about a leap new version?

Notifications through which mechanism? Leap versions aren't released *that* frequently, you might as well subscribe to openSUSE release mailing list :-)

In the current implementation, zypper services are provided locally -- new migration targets would become available as you install a package update that has new services included.  `%post` scriptlet could probably trigger a notification if there are new targets.

Alternatively, the services could also be hosted on download.opensuse.org -- the script would need to be reworked to discover new services, it could also trigger a notification once new targets are available.

However, I'm not sure which universal notification mechanism exists, other than sending mail locally.



> 2. I noticed the lack of the option to migrate to tumbleweed... is it coming later?

Oh yeah, I'll add Tumbleweed, that's pretty easy to do -- most recent stuff in https://download.opensuse.org/tumbleweed/, though (not https://download.opensuse.org/history/ -- `tumbleweed-cli` supposedly is for that)



> 3. Where is the GUI going to be integrated (yast-migration or a new yast module)?

Well, it's written in Ruby -- so it's certainly doable. Somebody just needs to do it :-)
`yast-migration` is for SLES migration (which is mostly driven by server-side logic of SCC), so it would probably have to be a new module.

**Comment by maverick74** [comment]
@ikapelyukhin Hi :)

regarding 1. - I was thinking about a simple "popup" - as any other regular OS notification that usually appears over the clock - indicating a new Leap version has became available, maybe with a launch button to start the upgrade process.

This button would naturally depend on point 3 - as it would launch a simple GUI - or at least launch a terminal window showing the process progress - (which i thought was in the scope of the project) that would perform the upgrade.

The idea was to do this in a way it would not scare "grandma" (or users like her) that are used to upgrade OS on the touch of a button (windows, *buntu, macos). So, a notification with button that would launch the process (even if it would show the terminal) without the user having to type in anything (other that the password), would be great :)

**Comment by maverick74** [comment]
Use case (where grandma has openSUSE Leap 15.1):

1. openSUSE Leap 15.2 is released
2. A notifications pops' up over the clock saying "openSUSE Leap 15.2 is available. Would you like to Upgrade?" with a button labeled "Upgrade"
3. grandma clicks "Upgrade"
4. A new window pops up with openSUSE Leap 15.2 selected (grandma could alternatively select other migration targets in this window).
5. grandma clicks "Execute" and is asked for root password.

After she typed in the root password all the rest is automatic... she could just relax and go cross-stitching while the system upgrades itself.

This was the idea behind "Easy openSUSE Upgrade". But i also believe (and please correct me if i'm wrong) that from what you already have, it doesn't get much more work to get it to the state i mentioned in the 5 steps above

**Comment by ikapelyukhin** [comment]
Well, for now grandma will have to use the console -- some feedback is needed about the proposed approach from the broader community and openSUSE release management.

**Comment by ikapelyukhin** [comment]
In the meanwhile, I've added Tumbleweed as a migration target.

**Comment by maverick74** [comment]
OK, it's fine! She's already used to it by now ahahah :) and it's a step in the right direction, at least.

As an additional info i've created two images as a reference:

Notification:
![Notification](https://user-images.githubusercontent.com/14912461/60114232-ef5dc580-9762-11e9-9c0b-6297d4505462.png)

Migration window:
![Migration](https://user-images.githubusercontent.com/14912461/60113857-27b0d400-9762-11e9-8514-917988576fea.png)

**Comment by maverick74** [comment]
> some feedback is needed about the proposed approach from the broader community and openSUSE release management.

About this: i think the problem is that this "detail" never gets discussed by "the powers that be"...
And that's how this gets (at least as far as i can track it) already 7 years old...

(but i'm still very happy with the direction you're taking it to!!! Thank you for your work on it =)

**Comment by ikapelyukhin** [comment]
> About this: i think the problem is that this "detail" never gets discussed by "the powers that be"...
> And that's how this gets (at least as far as i can track it) already 7 years old...

Somebody has to keep poking right people at right times to keep things moving :slightly_smiling_face:

**Comment by maverick74** [comment]
yeah, but that's a bit difficult for an "outsider" (as someone that does not work on SUSE or that does not know who to poke).

i just hope it won't take another 7 years to go from where you'll get it to, to a nice GUI for grandpa (which, unlike grandma, does not know what the konsole is and doesn't even know english ahaha).

Maybe i'll poke you on the next hackweek ahahaha -> you seem the right person and the hackweek the right time ahahahah

**Comment by ikapelyukhin** [comment]
> yeah, but that's a bit difficult for an "outsider" (as someone that does not work on SUSE or that does not know who to poke).

Well, I guess it can be, but there's a lot of options -- from reddit, to mailing lists, to the openSUSE board.

> i just hope it won't take another 7 years to go from where you'll get it to, to a nice GUI for grandpa (which, unlike grandma, does not know what the konsole is and doesn't even know english ahaha).
> 
> Maybe i'll poke you on the next hackweek ahahaha -> you seem the right person and the hackweek the right time ahahahah

I've been known to contribute to some Yast modules :slightly_smiling_face:

**Comment by maverick74** [comment]
> I guess it can be, but there's a lot of options -- from reddit, to mailing lists, to the openSUSE board.

Yeah... But It's hard to get heard sometimes...

> I've been known to contribute to some Yast modules slightly_smiling_face

Nice! But is it possible to contact you from here, or is this a temporary account for this project?

Yast sure is one of openSUSE great tools that keeps getting better. It sure was a decisive feature on our choice

**Comment by ikapelyukhin** [comment]
> Yeah... But It's hard to get heard sometimes...

Yep, herding cats and organizing things is a job in itself. :slightly_smiling_face: 

> Nice! But is it possible to contact you from here, or is this a temporary account for this project?

You mean my Github account? No, it's pretty permanent. The email address is in the profile, too.
This project hopefully will move into https://github.com/openSUSE/ namespace if all goes well.

**Comment by maverick74** [comment]
@ikapelyukhin so... how did it go? :)

**Comment by ikapelyukhin** [comment]
@maverick74 ¯\\\_(ツ)_/¯
Haven't really heard back from anybody, it's vacation season.

**Comment by maverick74** [comment]
LOL! Nice! 😁

**Comment by maverick74** [comment]
Did anyone return from their vacations already?

If not, either those vacations went very wrong or I'm going to get one of those jobs for myself!!!

LOL

**Comment by ikapelyukhin** [comment]
@maverick74 nope, still nothing. Maybe during the next hackweek :slightly_smiling_face: 
There's a vote for renaming openSUSE, though :grimacing:

**Comment by maverick74** [comment]
Yes, I was aware of that vote... Weird thing!

I hope it keeps the name - I'm used to it. 
But will not vote for myself. I trust there are people with better knowledge than me to make such decisions!

(oh... And I'm hopping that next hackweek *someone* will finish the job (with a GUI) 😂 )

**Comment by maverick74** [comment]
Hi.
Happy new year :)

Hey... you aware a new hackweek is coming next month?

Aaaaany plans for it :) - some GUI, maybe? 

LOL

**Comment by ikapelyukhin** [comment]
@maverick74 nope. There's no interest -- I'm going to archive this repo.

**Comment by ikapelyukhin** [comment]
@maverick74 Give [this notification implementation](https://github.com/ikapelyukhin/dbus-notification-test) a try. Should produce a notification like this:

![image](https://user-images.githubusercontent.com/1793699/72902097-3167dd80-3d2b-11ea-8d3f-3b38a3d79462.png)

**Comment by maverick74** [comment]
it looks **VERY** cool!!! 

I'm on Plasma (not on gnome). Will it work just as well?

 if it does, I might need some help/instruction on how to compile and test it.
I don't program anything in a few years and i'm very rusted at it...

**Comment by ikapelyukhin** [comment]
@maverick74 it sends those notifications on D-Bus, that's as close to a universal implementation as it can get. KDE should support it as well, so give it a try.
It's just a Ruby script, so just clone the repo and run it. The only dependency is `ruby-dbus`, Yast probably pulls it in, so you probably have it installed already.

**Comment by maverick74** [comment]
I'll give it a try asap (but it can take a few days as work is at it's highest peak right now and I might need some help as well...).

But, since the repo has been unarchived, do you have any plans to try to develop some kind of GUI for it?
I'm asking this in order to provide somekind of update over the hackweek page idea. :)

**Comment by ikapelyukhin** [comment]
@maverick74 a Yast module needs to be developed for the UI. I don't plan on writing it, though, I'd rather do something else instead.

**Comment by maverick74** [comment]
It work great!!!

![Screenshot_20200204_101412](https://user-images.githubusercontent.com/14912461/73735528-4f740b80-4737-11ea-9fcd-f98bfd760fe1.png)


Sorry for taking so long, however...

**Comment by ikapelyukhin** [comment]
@maverick74 Great, then it solves the issue of the notification mechanism. :slightly_smiling_face: 
The script should probably be executed as the `%post` script of the RPM package.

**Comment by maverick74** [comment]
But how do you plan on letting it know about new openSUSE versions? (some file on a server?)

Asking this, if i'm deducing your idea correctly (sorry, english is not my main language)...

from what i understand, the idea would be that, once the software is installed, it would perform regularly checks for a new version. On detect a new version it would notify the user and on button press it would invoke the script... (did i miss anything?)

**Comment by ikapelyukhin** [comment]
@maverick74 all the zypper services for all of the versions are bundled in the package: https://github.com/ikapelyukhin/opensuse-migration/tree/master/services

So new versions come via package updates. When the update is installed, the script running on `%post` would check most recent version available vs. what's currently installed and display a notification if there's something newer available.
